---
title: "BrailleR and Visualizations"
subtitle: "INFO526: Project 2"
author: 
  - name: "4X4"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "A deep dive into the R Package BrailleR which is a tool that makes visualizations in R more accessible to visually-impared users. The accessible feature is the creatation of a text-description of a given plot."
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
---

## High Level Goal

For Project 2, we want to explore the R package BrailleR.

## Research Question

How effective of a tool is BrailleR in terms of accessibility for creating alternative text of plots created in R for visually impaired users?\

## Description of Goals

BrailleR is fairly new R package (released in 2023) that creates alternative text (text descriptions) AKA "alt text" of visualizations that visually impared users can more easily access via screen-readers than pure visualizations. We want to demonstrate how to use it as well as analyze how effective of an accessibility tool it is based on the quality of the alt text. The reason that we chose this data set is because accessibility and inclusion are important and being able to see a plot is something that a lot of individuals take for granted.

In order to accomplish this, we will use a a series of cherry picked data sets that easily translates to different types of plot of varying complexity.The goal is to use various plots such as bar plots, pie charts, histograms, regression plot, time series, and heatmaps. For each plot, BrailleR will be used to create alt text for it. Effective alt text should contain short and long descriptions, translations of data into appropriate descriptions, and limit search engine optimization word choice. Because of its relatively recent release, we expect BrailleR to not be able to create accessible alt text for all visualizations and want to highlight its current limitations.

## Data Sets We Are Using and How

We are utilizing the World Happiness Report dataset and the Gold Price dataset from Kaggle to create insightful visualizations through which we can explore the capabilities of BrailleR.

Source for World Happiness Report dataset: <https://www.kaggle.com/datasets/unsdsn/world-happiness>

Source for Gold Prices for 5 years: <https://www.kaggle.com/datasets/kusumakar/gold-prices-for-5-years-financial-predictions>

-   For the regression plot, we are analyzing the relationship between GDP per capita and the Happiness Score, showcasing how economic prosperity influences happiness levels across countries.

-   A bar plot highlights the Happiness Scores of various countries, providing a visual ranking.

-   A pie chart to explore the relationship between countries and their perceptions of corruption.

-   A correlation heatmap to visualize the relationship among the numerical variables representing the quality of life in different countries within the happiness data set. This includes the attributes: GDP per capita, Social support, Healthy life expectancy, Freedom to make life choices, Generosity, Perceptions of corruption

-   Additionally, we are plotting a time series plot and histogram to illustrating trends and distributions in gold prices over time. For this purpose the attributes date and close will be used for the time series and attribute close will be used to plot the histogram.

## Plan of Attack

| Task Name               | Status      | Assignee                 | Due    | Priority | Summary                                          |
|---------------------|---------------------|----------------------|-----------|-----------|-------------------|
| Proposal                | In Progress | Kapua w/ input from Team | Nov 13 | High     | Develop and Create Project Proposal              |
| Find dataset 1          | Complete    | Nikhil                   | Nov 13 | Med      | Find dataset for all plots (except time series)  |
| Find dataset 2          | Complete    | Tanmay/Krisha            | Nov 13 | Med      | Find dataset for Time Series                     |
| Create Time Series Plot |             | Tanmay                   | Nov 20 | High     | Time Series of Gold Price                        |
| Create Histogram Plot   |             | Nikhil                   | Nov 20 | High     | Histogram of gold for daily price changes        |
| Create Regression Plot  |             | Tanmay                   | Nov 20 | High     | Regression of GDP and Happiness Score            |
| Create Bar Plot         | Completed   | Kapua                    | Nov 20 | High     | Bar Plot of Country and Happiness Score          |
| Create Pie Chart        | Completed   | Kapua                    | Nov 20 | High     | Statistics of US Age Groups                      |
| Create Heatmap          |             | Krisha                   | Nov 20 | High     | Correlation of numerical variables for happiness |
| Write-Up                |             | Team                     | Dec 13 | High     |                                                  |
| Poster                  |             | Team                     | Dec 01 | High     |                                                  |

## Project Repo

-   index.qmd - Project Write-Up

-   project.r - Project Code

-   proposal.qmd - Project Proposal

-   readme.md

-   data

    -   Gold Prices.csv

    -   world_happiness_report_2019.csv

    -   readme.md

-   Presentation

    -   presentation.pdf - Project Presentation Poster

    -   visualizations - images of the plots
